[project]
name = "kbot-installer"
version = "2025.03-dev"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Korantin Lévêque", email = "korantin.leveque@konverso.ai" }
]
requires-python = "==3.10.15"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["core/python", "rest"]
py-modules = ["Bot", "Load", "Learn", "System"]

[tool.hatch.build.targets.wheel.sources]
"core/python" = "."
"rest" = "."
